const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {evaluateEconomics,PRICING_POLICY}=require('../src/services/pricing.ts');
function fixture(overrides={}){
 const at=new Date().toISOString(),amount=n=>({amount:n,source:'ml_live',observedAt:at,evidence:'ML',contextKey:'same'});
 const memory=evaluateEconomics({price:100,cost:60,offerId:'offer',supplierId:'supplier',costObservedAt:at,fee:amount(15),shipping:amount(5),variableCosts:{...amount(0),source:'confirmed'},tax:{rate:.05,status:'confirmed',referenceMonth:'2026-09',source:'pgdas',observedAt:at,evidence:'confirmed',rbt12:null,missingMonths:[]},evaluatedAt:at});
 const state={memory,baseline:memory,applied:[],approval:{id:'approval',new_price:100,previous_price:100,ml_item_id:'MLB1',evaluation_id:'eval',payload:{}},remotePrice:100,group:{complete:true,groupId:'item:MLB1',itemIds:['MLB1']},linkedProduct:'p',...overrides};
 const client={from:table=>{const filters={};const query={select:()=>query,eq:(k,v)=>(filters[k]=v,query),in:()=>query,contains:()=>query,limit:()=>query,maybeSingle:async()=>({data:result()}),then:resolve=>resolve({data:result()})};const result=()=>table==='pricing_events'?filters.event_type==='APPROVED'?state.approval:state.applied:table==='current_pricing_evaluations'?{memory:state.baseline}:table==='anuncios_ml'?{produto_id:state.linkedProduct}:null;return query;}};
 const mocks={'./pricing-context':{evaluateProductPricing:async()=>({memory:state.memory,product:{sku:'VTK1'},runtime:{policy:PRICING_POLICY}})},'./integration':{fetchMLResult:async p=>({ok:true,data:p.endsWith('/prices')?{prices:[{type:'standard',conditions:{min_purchase_unit:1}}]}:{price:state.remotePrice}})},'./ml-pricing-group':{resolveMlPricingGroup:async()=>state.group},'../lib/ml/pricing-experiment':{getHighMarginPricingExperiment:async()=>null,activePricingExperimentSkus:()=>new Set()}};
 const filename=path.resolve(__dirname,'../src/services/pricing-approval.ts'),mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:mod,exports:mod.exports,require:id=>mocks[id]??require(id),Date,JSON,Set});
 return {state,run:()=>mod.exports.verifyPricingApproval(client,{approvalId:'approval',productId:'p',itemId:'MLB1',price:100})};
}
test('aprovação vinculada às mesmas entradas pode prosseguir sem teto artificial de margem',async()=>{const f=fixture();assert.ok(f.state.memory.margin>f.state.memory.band.limit);const r=await f.run();assert.equal(r.approval.id,'approval');});
test('aprovação ausente ou já aplicada não autoriza outra escrita',async()=>{await assert.rejects(fixture({approval:null}).run(),/PRICING_APPROVAL_REQUIRED/);await assert.rejects(fixture({applied:[{id:'applied'}]}).run(),/APROVACAO_JA_UTILIZADA/);});
test('mudança de custo ou preço anterior invalida aprovação',async()=>{const f=fixture();f.state.memory={...f.state.memory,cost:61};await assert.rejects(f.run(),/APROVACAO_ECONOMICA_DESATUALIZADA/);await assert.rejects(fixture({remotePrice:99}).run(),/PRECO_ANTERIOR_ALTERADO/);});
test('fonte inconclusiva e grupo divergente impedem aplicação',async()=>{const f=fixture();f.state.memory={...f.state.memory,result:null};await assert.rejects(f.run(),/INCONCLUSIVO_FONTE_ML_INDISPONIVEL/);await assert.rejects(fixture({group:{complete:false}}).run(),/VINCULO_INCONCLUSIVO/);await assert.rejects(fixture({linkedProduct:'other'}).run(),/GRUPO_ECONOMICO_DIVERGENTE/);});
