const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const ts=require('typescript');
const {PRICING_POLICY,evaluateEconomics,solveQuotedPrice}=require('../src/services/pricing.ts');const {buildPricingTaxContext}=require('../src/services/pricing-tax.ts');
function loadContext(fetcher){const filename=path.resolve(__dirname,'../src/services/pricing-context.ts');const mod={exports:{}};const code=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{module:mod,exports:mod.exports,require:id=>id==='./integration'?{fetchMLResult:fetcher}:require(id.startsWith('.')?path.resolve(path.dirname(filename),id):id),URLSearchParams,Date,Intl,console,Map,Set});return mod.exports;}
const at='2026-09-05T12:00:00Z';const tax=buildPricingTaxContext({referenceMonth:'2026-09',activityStartDate:'2026-03-23',monthlyRevenue:[],observedAt:at,confirmed:{month:'2026-09',rate:.05,evidence:'pgdas'}});
const input={price:100,product:{id:'product',ml_shipping:300,updated_at:'2026-01-01'},offer:{id:'offer',custo:60,dslite_fornecedor_id:'supplier',updated_at:at},runtime:{policy:PRICING_POLICY,tax,variableCosts:{product:0}},context:{sellerId:'seller',categoryId:'cat',listingType:'gold_special',shippingMode:'me2',logisticType:'xd_drop_off',freeShipping:true,dimensions:'10x10x10,500'},evaluatedAt:at};
test('integração tarifa total sem duplicar fixed_fee; frete vivo vence stale',async()=>{const {quoteMlEconomics}=loadContext(async p=>({ok:true,data:p.includes('listing_prices')?[{listing_type_id:'gold_special',sale_fee_amount:15,sale_fee_details:{fixed_fee:6}}]:{coverage:{all_country:{list_cost:5}}}}));const m=await quoteMlEconomics({...input,requireLive:true});assert.equal(m.fee.amount,15);assert.equal(m.shipping.amount,5);assert.equal(m.result,15);assert.equal(m.status,'available');});
test('ML indisponível não confirma prejuízo por frete local',async()=>{const {quoteMlEconomics}=loadContext(async()=>({ok:false,status:503}));const m=await quoteMlEconomics({...input,requireLive:true});assert.equal(m.result,null);assert.equal(m.status,'inconclusive');assert.equal(m.reasons[0],'INCONCLUSIVO_FONTE_ML_INDISPONIVEL');assert.equal(m.diagnostics.includes('PREJUIZO_REAL'),false);});
test('fallback configurado é explícito e nunca sobrescreve fonte viva',async()=>{const {quoteMlEconomics}=loadContext(async p=>p.includes('listing_prices')?{ok:true,data:{listing_type_id:'gold_special',sale_fee_amount:10}}:{ok:false});const m=await quoteMlEconomics(input);assert.equal(m.fee.amount,10);assert.equal(m.shipping.source,'local');assert.equal(m.status,'estimated');});
test('Radar, anúncio e simulador compartilham os mesmos valores e cotação final',async()=>{const {quoteMlEconomics}=loadContext(async p=>({ok:true,data:p.includes('listing_prices')?{listing_type_id:'gold_special',sale_fee_amount:10}:{coverage:{all_country:{list_cost:5}}}}));const quote=p=>quoteMlEconomics({...input,price:p,requireLive:true});const radar=await solveQuotedPrice({cost:60,taxRate:.05,initialPrice:100,objective:'target',quote});const simulator=await solveQuotedPrice({cost:60,taxRate:.05,initialPrice:600,objective:'target',quote});assert.equal(radar.ok,true);assert.equal(simulator.ok,true);assert.equal(radar.memory.price,simulator.memory.price);assert.deepEqual(radar.memory,await quote(radar.memory.price));});
test('solver detecta oscilação em cotação descontínua',async()=>{const quote=async price=>evaluateEconomics({price,cost:60,offerId:'o',supplierId:'s',costObservedAt:at,fee:{amount:price<100?50:0,source:'ml_live',observedAt:at,evidence:'q'},shipping:{amount:0,source:'ml_live',observedAt:at,evidence:'q'},variableCosts:{amount:0,source:'confirmed',observedAt:at,evidence:'config'},tax,evaluatedAt:at});const result=await solveQuotedPrice({cost:60,taxRate:.05,initialPrice:100,objective:'target',quote});assert.equal(result.ok,false);assert.equal(result.reason,'PRECIFICACAO_NAO_CONVERGIU');});
test('escolha de oferta impede fornecedor inativo de fornecer CMV',async()=>{const {resolvePricingProduct}=loadContext(async()=>({ok:false}));const responses={produtos:{id:'p',oferta_preferencial_id:'inactive',fornecedor_preferencial_manual:true},produto_fornecedor_ofertas:[{id:'inactive',ativo:true,custo:1,estoque:9,dslite_fornecedor_id:'disabled'},{id:'active',ativo:true,custo:60,estoque:1,dslite_fornecedor_id:'enabled'}],fornecedores:[{dslite_id:'disabled',ativo:false},{dslite_id:'enabled',ativo:true}]};const client={from:t=>({select:()=>({eq:()=>({then:resolve=>resolve({data:responses[t]}),single:async()=>({data:responses[t]})}),then:resolve=>resolve({data:responses[t]})})})};const result=await resolvePricingProduct(client,'p');assert.equal(result.offer.id,'active');});
test('observação ML válida vence fallback quando nova consulta falha',async()=>{const liveContext=loadContext(async p=>({ok:true,data:p.includes('listing_prices')?{listing_type_id:'gold_special',sale_fee_amount:9}:{coverage:{all_country:{list_cost:4}}}}));const observed=await liveContext.quoteMlEconomics({...input,requireLive:true});const offline=loadContext(async()=>({ok:false,status:503}));const memory=await offline.quoteMlEconomics({...input,observedMemory:observed});assert.equal(memory.fee.amount,9);assert.equal(memory.shipping.amount,4);assert.equal(memory.fee.source,'ml_observed');assert.equal(memory.shipping.source,'ml_observed');const changed=await offline.quoteMlEconomics({...input,price:101,observedMemory:observed});assert.equal(changed.fee.source,'fallback');});
