export interface QuestionHomologationFixture {
  id: number;
  itemId: string;
  anuncio: string;
  anuncioUrl: null;
  anuncioStatus: string | null;
  thumbnail: string | null;
  cliente: string;
  clienteId: number;
  pergunta: string;
  resposta: string | null;
  dataPergunta: string;
  dataResposta: string | null;
  status: string;
  mlStatus: string;
  respostaStatus: string | null;
  hold: boolean;
  removidaDoAnuncio: boolean;
  tags: string[];
  categoriasIa: string[];
  isHomologationFixture: true;
}

// Temporário: manter ativo somente durante a aprovação visual de BNT-D06 em dev.
export const BNT_D06_VISUAL_REVIEW = true;

function minutesBefore(now: Date, minutes: number) {
  return new Date(now.getTime() - minutes * 60_000).toISOString();
}

export function createQuestionHomologationFixtures(
  now = new Date(),
): QuestionHomologationFixture[] {
  return [
    {
      id: -17001,
      itemId: 'MLB-HML-1001',
      anuncio: 'Furadeira de Impacto Profissional 850W com Maleta e Acessórios',
      anuncioUrl: null,
      anuncioStatus: 'active',
      thumbnail: '/branding/bentevi/icon-192.png',
      cliente: 'Cliente de teste 101',
      clienteId: 99000101,
      pergunta: 'Boa tarde! A furadeira acompanha brocas para concreto e madeira ou vem somente com a maleta?',
      resposta: null,
      dataPergunta: minutesBefore(now, 14),
      dataResposta: null,
      status: 'pendente',
      mlStatus: 'UNANSWERED',
      respostaStatus: null,
      hold: false,
      removidaDoAnuncio: false,
      tags: [],
      categoriasIa: ['produto'],
      isHomologationFixture: true,
    },
    {
      id: -17002,
      itemId: 'MLB-HML-1002',
      anuncio: 'Câmera de Segurança Wi-Fi Full HD com Visão Noturna',
      anuncioUrl: null,
      anuncioStatus: 'active',
      thumbnail: '/branding/bentevi/bentevi-mark.png',
      cliente: 'Cliente de teste 102',
      clienteId: 99000102,
      pergunta: 'Consigo acompanhar duas câmeras ao mesmo tempo pelo celular? O aplicativo funciona em Android e iPhone?',
      resposta: null,
      dataPergunta: minutesBefore(now, 52),
      dataResposta: null,
      status: 'pendente',
      mlStatus: 'UNANSWERED',
      respostaStatus: null,
      hold: false,
      removidaDoAnuncio: false,
      tags: [],
      categoriasIa: ['compatibilidade'],
      isHomologationFixture: true,
    },
    {
      id: -17003,
      itemId: 'MLB-HML-1003',
      anuncio: 'Jogo de Panelas Antiaderente 10 Peças com Tampa de Vidro',
      anuncioUrl: null,
      anuncioStatus: 'active',
      thumbnail: null,
      cliente: 'Cliente de teste 103',
      clienteId: 99000103,
      pergunta: 'Pode usar em fogão de indução? Também gostaria de saber o diâmetro de cada panela porque o espaço do meu armário é pequeno.',
      resposta: null,
      dataPergunta: minutesBefore(now, 185),
      dataResposta: null,
      status: 'pendente',
      mlStatus: 'UNANSWERED',
      respostaStatus: null,
      hold: false,
      removidaDoAnuncio: false,
      tags: [],
      categoriasIa: ['especificacao'],
      isHomologationFixture: true,
    },
    {
      id: -17004,
      itemId: 'MLB-HML-1004',
      anuncio: 'Parafusadeira a Bateria 21V com Duas Baterias e Carregador Bivolt',
      anuncioUrl: null,
      anuncioStatus: 'active',
      thumbnail: '/branding/bentevi/icon-192.png',
      cliente: 'Cliente de teste 104',
      clienteId: 99000104,
      pergunta: 'Preciso usar a ferramenta para montagem de móveis durante o dia inteiro. Qual é a autonomia aproximada de cada bateria e quanto tempo demora uma carga completa? A maleta tem espaço para guardar as duas baterias, o carregador e um conjunto pequeno de bits?',
      resposta: null,
      dataPergunta: minutesBefore(now, 1_570),
      dataResposta: null,
      status: 'pendente',
      mlStatus: 'UNANSWERED',
      respostaStatus: null,
      hold: false,
      removidaDoAnuncio: false,
      tags: [],
      categoriasIa: ['especificacao', 'produto'],
      isHomologationFixture: true,
    },
    {
      id: -17005,
      itemId: 'MLB-HML-1005',
      anuncio: 'Aspirador Vertical 2 em 1 1200W com Filtro HEPA Lavável',
      anuncioUrl: null,
      anuncioStatus: 'active',
      thumbnail: null,
      cliente: 'Cliente de teste 105',
      clienteId: 99000105,
      pergunta: 'Tem pronta entrega para o CEP 30130-010?',
      resposta: null,
      dataPergunta: minutesBefore(now, 4_360),
      dataResposta: null,
      status: 'pendente',
      mlStatus: 'UNANSWERED',
      respostaStatus: null,
      hold: false,
      removidaDoAnuncio: false,
      tags: [],
      categoriasIa: ['entrega'],
      isHomologationFixture: true,
    },
    {
      id: -17006,
      itemId: 'MLB-HML-1006',
      anuncio: 'Caixa de Som Bluetooth Portátil 40W à Prova de Respingos',
      anuncioUrl: null,
      anuncioStatus: 'active',
      thumbnail: '/branding/bentevi/bentevi-mark.png',
      cliente: 'Cliente de teste 106',
      clienteId: 99000106,
      pergunta: 'Ela conecta com outra caixa igual para tocar em estéreo?',
      resposta: 'Sim. Duas unidades do mesmo modelo podem ser pareadas pelo modo TWS para reprodução em estéreo.',
      dataPergunta: minutesBefore(now, 390),
      dataResposta: minutesBefore(now, 345),
      status: 'respondida',
      mlStatus: 'ANSWERED',
      respostaStatus: 'ACTIVE',
      hold: false,
      removidaDoAnuncio: false,
      tags: [],
      categoriasIa: ['compatibilidade'],
      isHomologationFixture: true,
    },
    {
      id: -17007,
      itemId: 'MLB-HML-1007',
      anuncio: 'Kit Ferramentas Manuais com 129 Peças e Maleta Reforçada',
      anuncioUrl: null,
      anuncioStatus: 'active',
      thumbnail: null,
      cliente: 'Cliente de teste 107',
      clienteId: 99000107,
      pergunta: 'As chaves são de aço cromo vanádio?',
      resposta: 'Sim. As chaves e os soquetes do conjunto são produzidos em aço cromo vanádio.',
      dataPergunta: minutesBefore(now, 1_600),
      dataResposta: minutesBefore(now, 1_520),
      status: 'respondida',
      mlStatus: 'ANSWERED',
      respostaStatus: 'ACTIVE',
      hold: false,
      removidaDoAnuncio: false,
      tags: [],
      categoriasIa: ['especificacao'],
      isHomologationFixture: true,
    },
    {
      id: -17008,
      itemId: 'MLB-HML-1008',
      anuncio: 'Luminária de Mesa LED Articulada com Controle de Intensidade',
      anuncioUrl: null,
      anuncioStatus: 'paused',
      thumbnail: '/branding/bentevi/icon-192.png',
      cliente: 'Cliente de teste 108',
      clienteId: 99000108,
      pergunta: 'A luz amarela é adequada para leitura noturna?',
      resposta: null,
      dataPergunta: minutesBefore(now, 880),
      dataResposta: null,
      status: 'under_review',
      mlStatus: 'UNDER_REVIEW',
      respostaStatus: null,
      hold: true,
      removidaDoAnuncio: false,
      tags: ['review'],
      categoriasIa: [],
      isHomologationFixture: true,
    },
    {
      id: -17009,
      itemId: 'MLB-HML-1009',
      anuncio: 'Organizador Modular Multiuso com Quatro Gavetas',
      anuncioUrl: null,
      anuncioStatus: 'closed',
      thumbnail: null,
      cliente: 'Cliente de teste 109',
      clienteId: 99000109,
      pergunta: 'Existe esse modelo na cor preta?',
      resposta: null,
      dataPergunta: minutesBefore(now, 7_300),
      dataResposta: null,
      status: 'closed_unanswered',
      mlStatus: 'CLOSED_UNANSWERED',
      respostaStatus: null,
      hold: false,
      removidaDoAnuncio: false,
      tags: [],
      categoriasIa: ['variacao'],
      isHomologationFixture: true,
    },
    {
      id: -17010,
      itemId: 'MLB-HML-1010',
      anuncio: 'Produto removido para demonstração do estado indisponível',
      anuncioUrl: null,
      anuncioStatus: 'closed',
      thumbnail: null,
      cliente: 'Cliente de teste 110',
      clienteId: 99000110,
      pergunta: '',
      resposta: null,
      dataPergunta: minutesBefore(now, 10_200),
      dataResposta: null,
      status: 'banned',
      mlStatus: 'BANNED',
      respostaStatus: null,
      hold: false,
      removidaDoAnuncio: true,
      tags: ['deleted'],
      categoriasIa: [],
      isHomologationFixture: true,
    },
  ];
}
